config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :posts do
      resource :likes
      get 'translate' => 'posts#translate', as: :translate
      get 'hide_translation' => 'posts#hide_translation', as: :hide_translation
    end
    resources :users do
      get 'wall' => 'users#wall', as: :wall
    end
    resource :session

    root 'posts#index'

    post 'user/:id/follow' => 'users#follow', as: :follow_user
    delete 'user/:id/unfollow' => 'users#unfollow', as: :unfollow_user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  paginates_per 2

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  validates :title, presence: true
  validates :body, length: { minimum: 25 }
  validates :readable_time, numericality: { greater_than: 0 }

  CATEGORIES = %w(events sports economy photography medicine other)
  LANGUAGES = %w(en es de)

  validates :category, inclusion: { in: CATEGORIES }
  validates :language, inclusion: { in: LANGUAGES }

  has_one_attached :image

  SORT_FILTER = [
    [I18n.t('posts.index.filter1'), 'time_desc'],
    [I18n.t('posts.index.filter2'), 'time_asc'],
    [I18n.t('posts.index.filter3'), 'size_long'],
    [I18n.t('posts.index.filter4'), 'size_short']
  ]

  LANGUAGE_FILTER = %w(English Español Deutsch)

  scope :time_asc, -> { order(created_at: :asc) }
  scope :time_desc, -> { order(created_at: :desc) }
  scope :size_long, -> { order('length(body) desc') }
  scope :size_short, -> { order('length(body) asc') }
  scope :language, ->(lang) { where(language: lang) }
  scope :search, ->(term) { where('body || title || category like ?', "%#{term}%") }

  def liked_by_current_user?(user)
    likes.find_by(user: user).present?
  end

  def name_likers
    likers.collect { |h| h.name.capitalize }.join(', ')
  end
end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 2

  acts_as_followable
  acts_as_follower

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :fav_posts, through: :likes, source: :post

  has_secure_password

  validates :name, presence: true
  validates :email, format: /\A\S+@\S+\z/, uniqueness: { case_sensitive: false }

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end

  def name_followers
    followers.collect { |h| h.name.capitalize }.join(', ')
  end

  def name_followings
    all_following.collect { |h| h.name.capitalize }.join(', ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def require_signin
    redirect_to root_path unless current_user
  end

  private
    def current_user
      current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

    def default_url_options(options = {})
      { locale: I18n.locale }.merge options
    end

    helper_method :current_user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_signin

  def create
    @post = Post.find(params[:post_id])
    @post.likes.create!(user: current_user) unless Like.find_by(post: @post, user: current_user)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = Like.find_by(post: @post, user: current_user)
    @like.destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_signin, except: [:index]

  def index
    # @prompt = 'Sort by...'
    # @prompt_lang = 'Select language...'
    @posts = Post.all.page params[:page] # kaminari pagination

    @posts = @posts.language(params[:language][0..1].downcase) unless params[:language].blank?
    @posts = @posts.send(params[:sort]) unless params[:sort].blank?

    @posts = @posts.search(params[:search]) unless params[:search].blank?
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(session[:user_id])
    @post = @user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def show
    @post = Post.find(params[:id])
    @complete = true
    @language_detected = MagicTranslation.apply.detect @post.body
  end

  def translate
    @post = Post.find(params[:post_id])
    @translated_text = MagicTranslation.apply.translate @post.body, from: @language_detected, to: params[:locale]
  end

  def hide_translation
    @post = Post.find(params[:post_id])
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :language, :readable_time, :category, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else 
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @users = User.all
  end

  def show
    @your_posts = current_user.posts.page params[:page]
    @liked_posts = current_user.fav_posts.page params[:page]
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow(@user)
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.stop_following(@user)
  end

  def wall
    @following = current_user.all_following
    @following_posts = Post.all.where(user: @following).order(created_at: :desc).page params[:page]
  end

  private 
    def user_params
      params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header id="site-header">
  <ul class="header-content">
    <%= content_tag :li do %>
      <%= link_to 'ESPAÑOL' , locale: :es %>
    <% end unless current_page?(locale: :es) %>
    <%= content_tag :li do %>
      <%= link_to 'ENGLISH', locale: :en %>
    <% end unless current_page?(locale: :en) %>
    <li><%= link_to t('header.link1'), posts_path %></li>
    <% if current_user %>
      <li><%= link_to t('header.link2'), user_wall_path(current_user) %></li>
      <li><%= link_to t('header.link3'), users_path %></li>
      <li><%= link_to t('header.link4'), new_post_path %></li>
      <li><%= link_to t('header.link5', name: current_user.name.capitalize), user_path(current_user) %></li>
      <li><%= link_to 'Log Out', session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Sign Up', new_user_path %></li>
      <li><%= link_to 'Log In', new_session_path %></li>
    <% end %>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield%>
    </div>
  </body>
</html>

app/views/likes/create.js.erb
$('#likes-<%= @post.id %>').html('<%= pluralize(@post.likes.size, 'Like') %>: <%= @post.name_likers %>')
$('#btn-likes-<%= @post.id %>').html('<%= j(render partial: 'posts/like_dislike', locals: { post: @post }) %>');

app/views/likes/destroy.js.erb
$('#likes-<%= @post.id %>').html('<%= pluralize(@post.likes.size, 'Like') %>: <%= @post.name_likers %>');
$('#btn-likes-<%= @post.id %>').html('<%= j(render partial: 'posts/like_dislike', locals: { post: @post }) %>');

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
<%= render 'shared/errors', object: @post %>
  <fieldset>
    <ul>
      <li>
          <%= f.label :title %>
          <%= f.text_field :title, autofocus: true %>
      </li>
      <li>
          <%= f.label :language %>
          <%= f.select :language, Post::LANGUAGES, prompt: t('shared.select') %>
      </li>
      <li>
          <%= f.label :readable_time %>
          <%= f.number_field :readable_time %>
      </li>
      <li>
          <%= f.label :category %>
          <%= f.select :category, Post::CATEGORIES, prompt: t('shared.select') %>
      </li>
      <li>
          <%= f.label :body %>
          <%= f.text_area :body, cols: 40, rows: 7 %>
      </li>
      <li>
        <%= f.label :image %>
        <%= f.file_field :image %>
      </li>
    </ul>
    <p>
      <%= f.submit %>
      <%= link_to t('shared.cancel'), posts_path %>
    </p>
  </fieldset>
<% end %>

app/views/posts/_like_dislike.html.erb
<% if post.liked_by_current_user?(current_user) %>
  <button><%= link_to t('posts.index.dislike'), post_likes_path(post.id), method: :delete, remote: true %></button>
<% else %>
  <button><%= link_to t('posts.index.like'), post_likes_path(post.id), method: :post, remote: true %></button>
<% end %>

app/views/posts/_post.html.erb
<li class="post-card">
  <h3><%= highlight post.title, params[:search] %></h3>
  <h4><%= t('posts.index.user') %>: <%= post.user.name %></h4>
  <h4><%= Post.human_attribute_name(:category) %>: <%= highlight post.category, params[:search] %></h4>
  <h4><%= Post.human_attribute_name(:language) %>: <%= post.language %></h4>
  <h4><%= Post.human_attribute_name(:readable_time) %>: <%= post.readable_time %></h4>
  <h4><%= t('posts.index.created') %>: <%= I18n.l(post.created_at, format: '%B %d, %Y') %></h4>

  <% if @complete %>
    <p><%= post.body %></p>
  <% else %>
    <p><%= highlight(truncate(post.body, length: 200, omission: "...") { link_to t('posts.index.read-more'), post }, params[:search]) %></p>
  <% end %>
  
  <div class="post-image-container">
    <% if post.image.attached? %>
      <%= image_tag(post.image, class: 'fit-image') %>
    <% end %>
  </div>
  <% if current_user %>
    <p>
      <%= link_to t('posts.index.edit'), edit_post_path(post) %>
      <%= link_to t('posts.index.delete'), post_path(post), method: :delete %>
    </p>
    <div id="btn-likes-<%= post.id %>">
      <%= render partial: 'posts/like_dislike', locals: { post: post } %>
    </div>
  <% end %>
  <div id="likes-<%= post.id %>">
    <%= pluralize(post.likes.size, 'Like') %>: <%= post.name_likers %>
  </div>
</li>

app/views/posts/edit.html.erb
<h1>Edit Post:</h1>

<%= render 'posts/form' %>

app/views/posts/hide_translation.js.erb
$('#translation-instructions').html('<%= link_to "Translate to #{params[:locale]}", post_translate_path(@post.id), method: :get, remote: true %>');
$('#translated-text').html('');

app/views/posts/index.html.erb
<%= form_tag posts_path, method: :get do %>
  <%= label_tag t('.search-label') %>
  <%= text_field_tag 'search', nil, placeholder: t('.search-placeholder') %>
  <%= submit_tag t('.search-btn') %>
<% end %>
<hr>

<h1><%= t('.title') %></h1>

<%= form_tag posts_path, method: :get do %>
  <%= select_tag 'language', options_for_select(Post::LANGUAGE_FILTER, selected: params[:language]), prompt: t('.select') %>
  <%= select_tag 'sort', options_for_select(Post::SORT_FILTER, selected: params[:sort]), prompt: t('.sort') %>
  <%= submit_tag t('.apply-btn') %>
<% end %>


<% if @posts.size != 0 %>
  <ul id="post-list">
    <%= render partial: 'posts/post', collection: @posts, as: :post %>
  </ul>
<% end %>

<div id="paginates">
  <%= paginate @posts, remote: true %>
</div>

app/views/posts/index.js.erb
$('#post-list').html('<%= j render partial: 'posts/post', collection: @posts, as: :post %>')
$('#paginates').html('<%= j paginate @posts, remote: true %>')

app/views/posts/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'posts/form' %>

app/views/posts/show.html.erb
<ul>
  <%= render partial: 'posts/post', locals: { post: @post } %>
</ul>

<% if @language_detected != params[:locale] %>
  <p id="translation-instructions"><%= link_to "Translate to #{params[:locale]}", post_translate_path(@post.id), method: :get, remote: true %></p>
<% end %>

<div id="translated-text"></div>

app/views/posts/translate.js.erb
$('#translation-instructions').html('<%= link_to 'Hide translation', post_hide_translation_path(@post.id), remote: true %>');
$('#translated-text').html('<%= j @translated_text %>');

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <header>
    <h2>Form could not be saved!</h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.count, 'error')%>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </header>
<% end %>

app/views/users/_follow_unfollow.html.erb
<% if current_user.following?(user) %>
  <button><%= link_to t('users.index.unfollow'), unfollow_user_path(user.id), method: :delete, remote: true %></button>
<% else %>
  <button><%= link_to t('users.index.follow'), follow_user_path(user.id), method: :post, remote: true %></button>
<% end %>

app/views/users/follow.js.erb
$('#followers-<%= @user.id %>').html('<%= pluralize(@user.followers.size,  t('users.index.follower')) %>: <%= @user.name_followers %>')
$('#btn-following-<%= @user.id %>').html('<%= j render partial: 'users/follow_unfollow.html.erb', locals: { user: @user } %> ');

app/views/users/index.html.erb
<h1><%= t('.title') %></h1>

<% if @users.size != 0 %>
  <% @users.each do |user| %>
    <ul>
      <li>
        <%= link_to "#{user.name.capitalize}", user_path(user.id) %>
        <p><%= user.email %></p>
        <% if user != current_user %>
          <div id="btn-following-<%= user.id %>">
            <%= render partial: 'users/follow_unfollow.html.erb', locals: { user: user } %>
          </div>
        <% end %>
        <p id="followers-<%= user.id %>">
          <%= pluralize(user.followers.size, t('.follower')) %>:
          <%= user.name_followers %>
        </p>
        <hr>
      </li>
    </ul>
  <% end %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>
<%= render 'shared/errors', object: @user %>
  <fieldset>
    <ol>
      <li>
        <%= f.label :name %>
        <%= f.text_field :name, size: 30, autofocus: true %>
      </li>
      <li>
        <%= f.label :username %>
        <%= f.text_field :username, size: 30 %>
      </li>
      <li>
        <%= f.label :email %>
        <%= f.email_field :email, size: 30 %>
      </li>
      <li>
        <%= f.label :password %>
        <%= f.password_field :password, size: 30 %>
      </li>
      <li>
        <%= f.label :password_confirmation, 'Confirm Password' %>
        <%= f.password_field :password_confirmation, size: 40 %>
      </li>
    </ol>
    <p>
      <%= f.submit 'Sign Up' %>
    </p>
  </fieldset>
<% end %>

app/views/users/show.html.erb
<h1><%= t('.title', name: current_user.name.capitalize) %></h1>
<p><%= current_user.email %></p>

<h2><%= t('.title-followers') %></h2>
<p><%= current_user.name_followers %></p>

<h2><%= t('.title-following') %></h2>
<p><%= current_user.name_followings %></p>

<h2><%= t('.title-your-posts') %></h2>
<ul id="your-post-list">
  <%= render partial: 'posts/post', collection: @your_posts, as: :post %>
</ul>
<div id="your-pagination">
  <%= paginate @your_posts, remote: true %>
</div>

<h2><%= t('.title-liked-posts') %></h2>
<ul id="liked-post-list">
  <%= render partial: 'posts/post', collection: @liked_posts, as: :post %>
</ul>
<div id="liked-pagination">
  <%= paginate @liked_posts, remote: true %>
</div>

app/views/users/show.js.erb
<% if @your_posts %>
  $('#your-post-list').html('<%= j render partial: 'posts/post', collection: @your_posts, as: :post %>')
  $('#your-pagination').html('<%= j paginate @your_posts, remote: true %>')
<% end %>

<% if @liked_posts %>
  $('#liked-post-list').html('<%= j render partial: 'posts/post', collection: @liked_posts, as: :post %>')
  $('#liked-pagination').html('<%= j paginate @liked_posts, remote: true %>')
<% end %>

app/views/users/unfollow.js.erb
$('#followers-<%= @user.id %>').html('<%= pluralize(@user.followers.size,  t('users.index.follower')) %>: <%= @user.name_followers %>')
$('#btn-following-<%= @user.id %>').html('<%= j render partial: 'users/follow_unfollow.html.erb', locals: { user: @user } %> ');

app/views/users/wall.html.erb
<h1><%= t('wall.title') %></h1>

<% if @following_posts.size != 0 %>
  <ul id="post-list-wall">
    <%= render partial: 'posts/post', collection: @following_posts, as: :post %>
  </ul>
<% end %>


<div id="paginates-wall">
  <%= paginate @following_posts, remote: true %>
</div>

app/views/users/wall.js.erb
$('#post-list-wall').html('<%= j render partial: 'posts/post', collection: @following_posts, as: :post %>')
$('#paginates-wall').html('<%= j paginate @following_posts, remote: true %>')